"""empty message

Revision ID: 2ab5fe27c8d3
Revises: b02ee088da22
Create Date: 2023-07-09 22:45:08.667989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ab5fe27c8d3'
down_revision = 'b02ee088da22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
