"""empty message

Revision ID: 34818f6caae7
Revises: de74d3450eec
Create Date: 2023-07-15 06:33:37.767160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34818f6caae7'
down_revision = 'de74d3450eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameSeries', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('videoGame', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('img_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('page_no', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('page_no')
        batch_op.drop_column('release_date')
        batch_op.drop_column('img_url')
        batch_op.drop_column('videoGame')
        batch_op.drop_column('gameSeries')

    # ### end Alembic commands ###
