"""empty message

Revision ID: b02ee088da22
Revises: f62037f44b90
Create Date: 2023-07-09 13:36:38.585826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02ee088da22'
down_revision = 'f62037f44b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tail_id', sa.String(), nullable=False))
        batch_op.drop_constraint('product_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['tail_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('product_name_key', ['name'])
        batch_op.drop_column('tail_id')

    # ### end Alembic commands ###
